version: "3.9"
services:
  aya-llm:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - "8008:8008"

volumes:
  datadb:
  weights: