[tool.poetry]
name = "aya-llm"
description = "Aya-LLM API package"
version = "0.1.0"
license = "MIT"
authors = [ 
    "Arsel Tindo <devtnga@gmail.com>",
    "Nathan Sarrazin <contact@nsarrazin.com>"
]

packages = [
    { include = "ayallm", from = "src" }
]

homepage = "https://ayallm.weloobe.com/"
repository = "https://github.com/umilab/aya-llm"

include = [{path="src"}]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python=">=3.9,<4.0"
asyncio = "^3.4.3"
packaging = "^23.1"
pydantic = "^1.10.7"
pymongo = "^4.3.3"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
pyyaml = "^6.0"
rfc3986 = "^2.0.0"
sentencepiece = "^0.1.99"
sniffio = "^1.3.0"
sse-starlette = "^1.5.0"
starlette = "^0.26.1"
toml = "^0.10.2"
tqdm = "^4.65.0"
typing-extensions = "^4.5.0"
ujson = "^5.7.0"
urllib3 = "^2.0.2"
uvicorn = "^0.22.0"
uvloop = "^0.17.0"
watchfiles = "^0.19.0"
websockets = "^11.0"
anyio = "^3.6.2"
certifi = "^2023.5.7"
charset-normalizer = "^3.1.0"
click = "^8.1.3"
email-validator = "^2.0.0"
fastapi = "^0.95.1"
filelock = "^3.12.0"
h11 = "^0.14.0"
httpcore = "^0.17.0"
httptools = "^0.5.0"
huggingface-hub = "^0.14.1"
idna = "^3.4"
itsdangerous = "^2.1.2"
jinja2 = "^3.1.2"
markupsafe = "^2.1.2"
motor = "^3.1.2"
orjson = "^3.8.12"
beanie = "^1.19.0"
dnspython = "^2.3.0"
lazy-model = "^0.0.5"
requests = "^2.30.0"
numpy = "^1.24.2"
langchain = "^0.0.230"
loguru = "^0.7.0"
redis = {extras = ["hiredis"], version = "^4.5.5"}
